micronaut:
  application:
    name: func_pay_sprint_gst
  server:
    cores:
      enabled: false
  security:
    token:
      jwt:
        enabled: true
    endpoints:
      logout:
        enabled: false
      login:
        enabled: false