micronaut:
  application:
    name: func_pay_sprint
  server:
    cors:
      enabled: true
  security:
    token:
      jwt:
        enabled: true
    endpoints:
      logout:
        enabled: false
      login:
        enabled: false